# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ChargeCoarsening',
                'doc_host': 'https://andrew-vh.github.io',
                'git_url': 'https://github.com/andrew-vh/ChargeCoarsening',
                'lib_path': 'ChargeCoarsening'},
  'syms': {'ChargeCoarsening.core': {'ChargeCoarsening.core.foo': ('core.html#foo', 'ChargeCoarsening/core.py')}}}
